### ISSUE TITLE
Crash sometimes when go back

### ISSUE THREAD

**Issue by QuentinosR** [QuentinosR/PA_BT_Update#1]

**Comment by QuentinosR** [comment]
I/flutter (12182): 👻 INFO 2024-05-02 20:14:51.273306 [caller info not available] Close Connection
D/BluetoothGatt(12182): cancelOpen() - device: xx:xx:xx:xx:21:44
D/BluetoothGatt(12182): setCharacteristicNotification() - uuid: 0000fff1-0000-1000-8000-00805f9b34fb enable: false
D/BluetoothGatt(12182): onClientConnectionState() - status=0 clientIf=6 device=xx:xx:xx:xx:21:44
D/BluetoothGatt(12182): close()
D/BluetoothGatt(12182): unregisterApp() - mClientIf=6
W/System.err(12182): io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | com.polidea.rxandroidble2.exceptions.BleDisconnectedException: Disconnected from MAC='XX:XX:XX:XX:XX:XX' with status 0 (GATT_SUCCESS)
W/System.err(12182): 	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
W/System.err(12182): 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.dispose(ObservableFlatMap.java:313)
W/System.err(12182): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
W/System.err(12182): 	at io.reactivex.internal.operators.observable.ObservableReplay$ReplayObserver.dispose(ObservableReplay.java:271)
W/System.err(12182): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
W/System.err(12182): 	at io.reactivex.internal.operators.observable.ObservableRefCount.timeout(ObservableRefCount.java:156)
W/System.err(12182): 	at io.reactivex.internal.operators.observable.ObservableRefCount.cancel(ObservableRefCount.java:103)
W/System.err(12182): 	at io.reactivex.internal.operators.observable.ObservableRefCount$RefCountObserver.dispose(ObservableRefCount.java:252)
W/System.err(12182): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
W/System.err(12182): 	at io.reactivex.internal.operators.mixed.CompletableAndThenObservable$AndThenObservableObserver.dispose(CompletableAndThenObservable.java:86)
W/System.err(12182): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
W/System.err(12182): 	at io.reactivex.internal.operators.mixed.SingleFlatMapObservable$FlatMapObserver.dispose(SingleFlatMapObservable.java:84)
W/System.err(12182): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
W/System.err(12182): 	at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.dispose(ObservableFlatMap.java:588)
W/System.err(12182): 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.disposeAll(ObservableFlatMap.java:510)
W/System.err(12182): 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.dispose(ObservableFlatMap.java:310)
W/System.err(12182): 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.disposeAll(ObservableFlatMap.java:504)
W/System.err(12182): 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.dispose(ObservableFlatMap.java:310)
W/System.err(12182): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.dispose(ObservableObserveOn.java:146)
W/System.err(12182): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
W/System.err(12182): 	at io.reactivex.internal.observers.LambdaObserver.dispose(LambdaObserver.java:102)
W/System.err(12182): 	at com.signify.hue.flutterreactiveble.channelhandlers.CharNotificationHandler.unsubscribeFromAllNotifications(CharNotificationHandler.kt:71)
W/System.err(12182): 	at com.signify.hue.flutterreactiveble.channelhandlers.CharNotificationHandler.onCancel(CharNotificationHandler.kt:29)
W/System.err(12182): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onCancel(EventChannel.java:231)
W/System.err(12182): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:199)
W/System.err(12182): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
W/System.err(12182): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
W/System.err(12182): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/System.err(12182): 	at android.os.Handler.handleCallback(Handler.java:958)
W/System.err(12182): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(12182): 	at android.os.Looper.loopOnce(Looper.java:222)
W/System.err(12182): 	at android.os.Looper.loop(Looper.java:314)
W/System.err(12182): 	at android.app.ActivityThread.main(ActivityThread.java:8594)
W/System.err(12182): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(12182): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
W/System.err(12182): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
W/System.err(12182): Caused by: com.polidea.rxandroidble2.exceptions.BleDisconnectedException: Disconnected from MAC='XX:XX:XX:XX:XX:XX' with status 0 (GATT_SUCCESS)
W/System.err(12182): 	at com.polidea.rxandroidble2.internal.connection.RxBleGattCallback$2.onConnectionStateChange(RxBleGattCallback.java:81)
W/System.err(12182): 	at android.bluetooth.BluetoothGatt$1$4.run(BluetoothGatt.java:342)
W/System.err(12182): 	at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:941)
W/System.err(12182): 	at android.bluetooth.BluetoothGatt.-$$Nest$mrunOrQueueCallback(Unknown Source:0)
W/System.err(12182): 	at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:337)
W/System.err(12182): 	at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:211)
W/System.err(12182): 	at android.os.Binder.execTransactInternal(Binder.java:1351)
W/System.err(12182): 	at android.os.Binder.execTransact(Binder.java:1282)
E/AndroidRuntime(12182): FATAL EXCEPTION: main
E/AndroidRuntime(12182): Process: com.example.kt_session, PID: 12182
E/AndroidRuntime(12182): io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | com.polidea.rxandroidble2.exceptions.BleDisconnectedException: Disconnected from MAC='XX:XX:XX:XX:XX:XX' with status 0 (GATT_SUCCESS)
E/AndroidRuntime(12182): 	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
E/AndroidRuntime(12182): 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.dispose(ObservableFlatMap.java:313)
E/AndroidRuntime(12182): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
E/AndroidRuntime(12182): 	at io.reactivex.internal.operators.observable.ObservableReplay$ReplayObserver.dispose(ObservableReplay.java:271)
E/AndroidRuntime(12182): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
E/AndroidRuntime(12182): 	at io.reactivex.internal.operators.observable.ObservableRefCount.timeout(ObservableRefCount.java:156)
E/AndroidRuntime(12182): 	at io.reactivex.internal.operators.observable.ObservableRefCount.cancel(ObservableRefCount.java:103)
E/AndroidRuntime(12182): 	at io.reactivex.internal.operators.observable.ObservableRefCount$RefCountObserver.dispose(ObservableRefCount.java:252)
E/AndroidRuntime(12182): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
E/AndroidRuntime(12182): 	at io.reactivex.internal.operators.mixed.CompletableAndThenObservable$AndThenObservableObserver.dispose(CompletableAndThenObservable.java:86)
E/AndroidRuntime(12182): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
E/AndroidRuntime(12182): 	at io.reactivex.internal.operators.mixed.SingleFlatMapObservable$FlatMapObserver.dispose(SingleFlatMapObservable.java:84)
E/AndroidRuntime(12182): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
E/AndroidRuntime(12182): 	at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.dispose(ObservableFlatMap.java:588)
E/AndroidRuntime(12182): 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.disposeAll(ObservableFlatMap.java:510)
E/AndroidRuntime(12182): 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.dispose(ObservableFlatMap.java:310)
E/AndroidRuntime(12182): 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.disposeAll(ObservableFlatMap.java:504)
E/AndroidRuntime(12182): 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.dispose(ObservableFlatMap.java:310)
E/AndroidRuntime(12182): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.dispose(ObservableObserveOn.java:146)
E/AndroidRuntime(12182): 	at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
E/AndroidRuntime(12182): 	at io.reactivex.internal.observers.LambdaObserver.dispose(LambdaObserver.java:102)
E/AndroidRuntime(12182): 	at com.signify.hue.flutterreactiveble.channelhandlers.CharNotificationHandler.unsubscribeFromAllNotifications(CharNotificationHandler.kt:71)
E/AndroidRuntime(12182): 	at com.signify.hue.flutterreactiveble.channelhandlers.CharNotificationHandler.onCancel(CharNotificationHandler.kt:29)
E/AndroidRuntime(12182): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onCancel(EventChannel.java:231)
E/AndroidRuntime(12182): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:199)
E/AndroidRuntime(12182): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/AndroidRuntime(12182): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(12182): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(12182): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(12182): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(12182): 	at android.os.Looper.loopOnce(Looper.java:222)
E/AndroidRuntime(12182): 	at android.os.Looper.loop(Looper.java:314)
E/AndroidRuntime(12182): 	at android.app.ActivityThread.main(ActivityThread.java:8594)
E/AndroidRuntime(12182): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12182): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
E/AndroidRuntime(12182): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
E/AndroidRuntime(12182): Caused by: com.polidea.rxandroidble2.exceptions.BleDisconnectedException: Disconnected from MAC='XX:XX:XX:XX:XX:XX' with status 0 (GATT_SUCCESS)
E/AndroidRuntime(12182): 	at com.polidea.rxandroidble2.internal.connection.RxBleGattCallback$2.onConnectionStateChange(RxBleGattCallback.java:81)
E/AndroidRuntime(12182): 	at android.bluetooth.BluetoothGatt$1$4.run(BluetoothGatt.java:342)
E/AndroidRuntime(12182): 	at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:941)
E/AndroidRuntime(12182): 	at android.bluetooth.BluetoothGatt.-$$Nest$mrunOrQueueCallback(Unknown Source:0)
E/AndroidRuntime(12182): 	at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:337)
E/AndroidRuntime(12182): 	at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:211)
E/AndroidRuntime(12182): 	at android.os.Binder.execTransactInternal(Binder.java:1351)
E/AndroidRuntime(12182): 	at android.os.Binder.execTransact(Binder.java:1282)

**Comment by QuentinosR** [comment]
Known issue : https://github.com/PhilipsHue/flutter_reactive_ble/issues/79

**Comment by QuentinosR** [comment]
https://github.com/PhilipsHue/flutter_reactive_ble#how-to-handle-the-ble-undeliverable-exception

**Comment by QuentinosR** [comment]
Patch added seems to work. exception still exists but doesn't crash the app
